apiVersion: kubeshare.nthu/v1
kind: SharePod
metadata:
  name: cuda-vector-add
  namespace: faas-share-fn
  labels:
    #"com.openfaas.scale.min": "1"
    "com.openfaas.scale.max": "5"
  annotations:
    "kubeshare/gpu_request": "0.1"
    "kubeshare/gpu_limit": "0.2"
    "kubeshare/gpu_mem": "3145728000"
spec:
  replicas: 1
  podSpec:
    terminationGracePeriodSeconds: 1
    containers:
      - name: cuda-vector-add
        image: "k8s.gcr.io/cuda-vector-add:v0.1"
