apiVersion: faasshare.tum/v1
kind: SharePod
metadata:
  name: mobilenet
  namespace: faas-share-fn
  labels:
    #"com.openfaas.scale.min": "1"
    "com.openfaas.scale.max": "5"
  annotations:
    "kubeshare/gpu_request": "0.1"
    "kubeshare/gpu_limit": "0.2"
    "kubeshare/gpu_mem": "3145728000"
spec:
  replicas: 1
  podSpec:
    terminationGracePeriodSeconds: 1
    initContainers:
      - name: mobilenet-init
        image: leslie233/mobilenet-init:test
        volumeMounts:
          - name: "mobilenet-model"
            mountPath: /model/mobilenet
    containers:
      - name: mobilenet-test
        # image: leslie233/mobilenet-2:index
        image: leslie233/mobilnet-test:shared
        command: [ "sh", "-c", "fwatchdog" ]
        volumeMounts:
          - mountPath: /model/mobilenet
            name: mobilenet-model
    volumes:
      - names: mobilenet-model
        hostPath:
        path: /model/mobilenet
              #type:
        #volumeMounts:
        #- name:


