apiVersion: faasshare.tum/v1
kind: SharePod
metadata:
  name: mobilenet
  namespace: faas-share-fn
  labels:
    #"com.openfaas.scale.min": "1"
    "com.openfaas.scale.max": "5"
  annotations:
    "kubeshare/gpu_request": "0.1"
    "kubeshare/gpu_limit": "0.2"
    "kubeshare/gpu_mem": "3145728000"
spec:
  replicas: 1
  podSpec:
    terminationGracePeriodSeconds: 1
    containers:
      - name: mobilenet-test
        image: leslie233/mobilenet-2:probe-2
        #image: leslie233/mobilenet-test:shared
        command: [ "sh", "-c", "fwatchdog" ]
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - /home/app/probe/probe.sh
          falureThreshold: 3
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 2
        startupProbe:
          exec:
            command:
            - /bin/bash
            - /home/app/probe/probe.sh
          failureThreshold: 30
          periodSeconds: 2
        #volumeMounts:
        #  - name: "mobilenet-model"
        #    mountPath: "/model/mobilenet"
        #volumes:
        # - name: "mobilenet-model"
        #hostPath:
        #  path: "/model/mobilenet"
              #type:
        #volumeMounts:
        #- name:


