apiVersion: faasshare.tum/v1
kind: SharePod
metadata:
  name: shufflenet
  namespace: faas-share-fn
  labels:
    #"com.openfaas.scale.min": "1"
    "com.openfaas.scale.max": "5"
  annotations:
    "kubeshare/gpu_request": "0.1"
    "kubeshare/gpu_limit": "0.2"
    "kubeshare/gpu_mem": "7480000000"
    #934 MiB of memory needed, need to change
spec:
  replicas: 1
  podSpec:
    terminationGracePeriodSeconds: 1
    containers:
      - name: shufflenet
        image: leslie233/shufflenet-test:model-probe-2
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - /home/app/probe/probe.sh
          falureThreshold: 3
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 2
        startupProbe:
          exec:
            command:
            - /bin/bash
            - /home/app/probe/probe.sh
          failureThreshold: 30
          periodSeconds: 2
        command: [ "sh", "-c", "fwatchdog" ]
