image: ghcr.io/openfaas/cron-connector:0.5.0

gatewayURL: http://gateway.openfaas:8080

# Invoke via the asynchronous function endpoint
asyncInvocation: false

# Set a contentType for all invocations
contentType: text/plain

nodeSelector: {}

tolerations: []

affinity: {}

basicAuth: true