---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: faas-share
    component: autoscaler
  name: autoscaler
  namespace: "faas-share"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaler
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "false"
      labels:
        app: autoscaler
    spec:
      volumes:
      - name: auth
        secret:
          secretName: basic-auth
      - name: license
        secret:
          secretName: openfaas-license
      containers:
      - name:  autoscaler
        resources:
            limits:
              memory: 256Mi
            requests:
              memory: 128Mi
        image: ghcr.io/openfaasltd/autoscaler:0.2.3
        imagePullPolicy: Always
        command:
          - "/usr/bin/autoscaler"
          - "-license-file=/var/secrets/license/license"
        env:
        - name: gateway_url
          value: "http://gateway.faas-share:8080/"
        - name: prometheus_host
          value: "prometheus.faas-share"
        - name: prometheus_port
          value: "9090"
        - name: faas_function_suffix
          value: ".faas-share-fn.svc.cluster.local"
        - name: secret_mount_path
          value: "/var/secrets/autoscaler"
        - name: basic_auth
          value: "true"
        volumeMounts:
        - name: license
          readOnly: true
          mountPath: "/var/secrets/license"
        - name: auth
          readOnly: true
          mountPath: "/var/secrets/autoscaler"
