---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: faas-share
    component: faas-controller
  name: faas-share-controller
  namespace: "openfaas"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: faas-share
    component: faas-controller
  name: faas-share-controller
  namespace: "faas-share-fn"
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - namespaces
      - endpoints
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: faas-share
    component: faas-controller
  name: faas-share-profiles
  namespace: "openfaas"
rules:
  - apiGroups:
      - "openfaas.com"
    resources:
      - "profiles"
    verbs:
      - "get"
      - "list"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: faas-share
    component: faas-controller
  name: faas-share-controller
  namespace: "faas-share-fn"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: faas-share-controller
subjects:
  - kind: ServiceAccount
    name: faas-share-controller
    namespace: "openfaas"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: faas-share
    component: faas-controller
  name: faas-share-profiles
  namespace: "openfaas"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: faas-share-profiles
subjects:
  - kind: ServiceAccount
    name: faas-share-controller
    namespace: "openfaas"
