---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: faas-share
    component: gateway
  name: gateway
  namespace: "faas-share"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
      labels:
        app: gateway
    spec:
      serviceAccountName: faas-share-operator
      volumes:
      - name: faas-netes-temp-volume
        emptyDir: {}
      containers:
      - name: gateway
        resources:
            requests:
              cpu: 50m
              memory: 120Mi
        image: ghcr.io/openfaas/gateway:0.21.3
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          timeoutSeconds: 5
        env:
        - name: read_timeout
          value: "65s"
        - name: write_timeout
          value: "65s"
        - name: upstream_timeout
          value: "60s"
        - name: functions_provider_url
          value: "http://127.0.0.1:8081/"
        - name: direct_functions
          value: "false"
        - name: direct_functions_suffix
          value: "faas-share-fn.svc.cluster.local"
        - name: function_namespace
          value: "faas-share-fn"
        - name: faas_nats_address
          value: "nats.faas-share.svc.cluster.local"
        - name: faas_nats_port
          value: "4222"
        - name: faas_nats_channel
          value: "faas-request"
        - name: scale_from_zero
          value: "true"
        - name: max_idle_conns
          value: "1024"
        - name: max_idle_conns_per_host
          value: "1024"
        volumeMounts:
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      - name: operator
        resources:
            requests:
              cpu: 50m
              memory: 120Mi
        image: ghcr.io/interstellarss/faas-share:v0.1.22
        imagePullPolicy: Always
        command:
          - ./faas-share
        env:
          - name: port
            value: "8081"
          - name: function_namespace
            value: "faas-share-fn"
          - name: profiles_namespace
            value: "faas-share"
          - name: read_timeout
            value: "60s"
          - name: write_timeout
            value: "60s"
          - name: image_pull_policy
            value: "Always"
          - name: http_probe
            value: "true"
          - name: set_nonroot_user
            value: "false"
          - name: readiness_probe_initial_delay_seconds
            value: "2"
          - name: readiness_probe_timeout_seconds
            value: "1"
          - name: readiness_probe_period_seconds
            value: "2"
          - name: liveness_probe_initial_delay_seconds
            value: "2"
          - name: liveness_probe_timeout_seconds
            value: "1"
          - name: liveness_probe_period_seconds
            value: "2"
          - name: cluster_role
            value: "false"
        ports:
        - containerPort: 8081
          protocol: TCP
