---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: faas-share
    component: gateway
  name: gateway-external
  namespace: "faas-share"
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31112
  selector:
    app: gateway
