---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: faas-share
    component: gateway
  name: gateway-external
  namespace: "faas-share"
spec:
  type: LoadBalancer
  externalIps:
  - 172.0.0.1
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: gateway
