---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: faas-share
    component: nats
  name: nats
  namespace: "openfaas"
spec:
  type: ClusterIP
  ports:
    - port: 4222
      protocol: TCP
      name: tcp
  selector:
    app: nats
