---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: faas-share-operator
  namespace: "faas-share"
  labels:
    app: faas-share
    component: faas-share-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: faas-share-operator-rw
  namespace: "faas-share-fn"
  labels:
    app: faas-share
    component: faas-share-operator
rules:
- apiGroups: ["kubeshare.nthu"]
  resources: ["sharepods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["faasshare.tum"]
  resources: ["sharepods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/log", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods", "endpoints", "pods/proxy", "pods/podIP"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: faas-share-profiles
  namespace: "faas-share"
  labels:
    app: faas-share
    component: openfaas-operator
rules:
- apiGroups: ["openfaas.com"]
  resources: ["profiles"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: faas-share-operator-rw
  namespace: "faas-share-fn"
  labels:
    app: faas-share
    component: faas-share-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: faas-share-operator-rw
subjects:
- kind: ServiceAccount
  name: faas-share-operator
  namespace: "faas-share"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: faas-share-operator-rw2
  namespace: "faas-share"
  labels:
    app: faas-share
    component: faas-share-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: faas-share-operator-rw
subjects:
- kind: ServiceAccount
  name: faas-share-operator
  namespace: "faas-share"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: faas-share
    component: openfaas-operator
  name: faas-share-profiles
  namespace: "faas-share"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: faas-share-profiles
subjects:
  - kind: ServiceAccount
    name: faas-share-operator
    namespace: "faas-share"
