---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: faas-share
    component: prometheus
  name: prometheus
  namespace: "openfaas"
spec:
  type: ClusterIP
  ports:
    - port: 9090
      protocol: TCP
  selector:
    app: prometheus
