---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: faas-share-prometheus
  namespace: "faas-share"
  labels:
    app: faas-share
    component: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: faas-share-prometheus
  labels:
    app: faas-share
    component: prometheus
rules:
- apiGroups: [""]
  resources:
    - services
    - endpoints
    - pods
    - nodes
    - nodes/proxy
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: faas-share-prometheus
  namespace: "faas-share-fn"
  labels:
    app: faas-share
    component: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: faas-share-prometheus
subjects:
- kind: ServiceAccount
  name: faas-share-prometheus
  namespace: "faas-share"
